name: Create and publish docker images

on: push

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: node:alpine

    strategy:
      matrix:
        image:
          - app

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image name
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            IMAGE_TAG=$GITHUB_HEAD_REF
          elif [ "$VERSION" == "master" ]; then
            IMAGE_TAG=latest
          else
            IMAGE_TAG=$VERSION
          fi
          echo "DOCKER_IMAGE=${{ secrets.DOCKER_USER }}/${{ matrix['image'] }}:$IMAGE_TAG" >> $GITHUB_ENV
      - name: Build docker image
        run: >-
          docker build docker/${{ matrix['image'] }}
          --label "org.label-schema.vcs-ref=$GITHUB_SHA"
          --tag $DOCKER_IMAGE
      - run: docker push $DOCKER_IMAGE